C   SUB ACCRCY.FOR

      SUBROUTINE ACCRCY(I, EK, MY, MAXMSH, MODEN, NPOINT,
     & MODQTY, MINMOD,
     & MAXMOD, H1N,
     & DH0, DH0SQ, DSED, *, *)

      INTEGER EXTPOL

      DOUBLE PRECISION CC0, CC1, H0, H1
      DOUBLE PRECISION TWOPI, PI, OMEGA
      DOUBLE PRECISION ERR1A, ERR1R, ERR2A, ERR2R
      DOUBLE PRECISION WNMIN, H1N
      DOUBLE PRECISION EIGREF, EIGMIN, EIGMAX, STIFF
      DOUBLE PRECISION EK(MODEN)
      DOUBLE PRECISION MY(MAXMSH,MODEN)
      DOUBLE PRECISION DH0(8), DSED(8), DH0SQ(8)

      COMMON /AB/ BETA(-1:3), SCATT(2), C2S, CC0, CC1, C2
      COMMON /FLAGPL/ FIRST, FLAGP, FLAGPU, EXTPOL, CORREC
      COMMON /EXPMAX/ TRESH, EPS, RRMAX, EPSDEF
      COMMON /GEN/ EIGREF, EIGMIN, EIGMAX, STIFF
      COMMON /G/ H0,H1
      COMMON /ITMAX/ MAXIT
      COMMON /LUIN/ LUIN, LUWRN, LUCHK
      COMMON /LUNIT/ LUPLP, LUPLT, LUPRT
      COMMON /MSHIST/ MH0(8), MSED(8), ICOUNT, USEOLD
      COMMON /PARAM3/ IMESH, NMESH, MSHRAT, OPTMZ
      COMMON /PARAM4/ MESHI, MESHN
      COMMON /RNGPRF/ NSECT, RKM
      COMMON /TRIGON/ TWOPI, PI, OMEGA

  340 FORMAT(1X,//,' *** WARNING FOR GROUP VELOCITY CALCULATION AT',
     & ' MESH ',I2,' *** ',/,
     & ' EXTRAPOLATED EIGENVALUES ARE NOT USED BECAUSE OF',
     & ' INSUFFICIENT ACCURACY.',/,
     & ' NON EXTRAPOLATED EIGENVALUES FROM LAST MESH ARE USED',
     & ' INSTEAD.',/,
     & ' MORE DENSE MESHES ARE NEEDED TO IMPROVE ACCURACY ')
  400 FORMAT(1X,/,' WARNING : THE ALLOWED MAX NUMBER OF MESH POINTS',
     & ' IS REACHED. ',/,' LARGER ARRAY SIZES WOULD BE NEEDED ')
  410 FORMAT(1X,/,' EXTRAPOLATED EIGENVALUES ARE CHOSEN. ')
  420 FORMAT(1X,/,' NON EXTRAPOLATED EIGENVALUES ARE CHOSEN. ')
  600 FORMAT(1X,//,' ***  MAX NUMBER OF ITERATIONS (',I2,') REACHED',
     & ' IN SUB ACCRCY  ***')
  620 FORMAT(1X,' *** SUB ACCRCY, EPS= ',E12.5,' ***',2X,'ABSOLUTE',
     & 8X,'RELATIVE',/,
     & '  MAX ERR ON     EXTRAP WN ',11X,D13.6,3X,D13.6,/,
     & '  MAX ERR ON NON EXTRAP WN ',11X,D13.6,3X,D13.6,/)
  831 FORMAT(1X,' SUB ACCRCY: MESH, ERR1R :',I3,2X,D15.8)
  840 FORMAT(1X,/,'  Max tolerated error on Wave Numbers at ',
     & 1PE9.3,' km :',2X,E12.6)
  860 FORMAT(1X ,' Max relative error on mesh # ',I2,20X,
     &           ' :',2x,1PE12.6)


      IF(EXTPOL .LE. 0)   THEN
       DO 1200   M=1,MODQTY
       EK(M)=SQRT(MY(I,M))/H0
 1200  CONTINUE
       IF( MESHN .EQ. 1 )   RETURN
      END IF

      WNMIN=OMEGA/DBLE(C2)
      WNMIN=(H0*WNMIN)**2

      CALL CONVRG(ERR1A,ERR1R,ERR2A,ERR2R,MODQTY,MESHN,
     &            MY,MAXMSH,MODEN,
     &            DH0SQ,H0,EK,EXTPOL,WNMIN)

CWRN      WRITE(LUWRN,831) MESHN+ICOUNT, ERR1R
      MAXMOD=MINMOD+MODQTY-1
      IF(MODQTY .LE. 0)   RETURN

      IF(MESHN .GE. 3)   THEN
       NPMAX=(MH0(MESHN-2) + MSED(MESHN-2))*2
      ELSE
       NPMAX=NPOINT
      END IF

      IF(RRMAX .EQ. 0)   THEN
        EPS= EPSDEF
      ELSE
CFMC        EPS=EK(1)/RRMAX
      EPS= TWOPI/(360*RRMAX)
        EPS=MAX(EPS,1.0E-12)
      END IF


      IF( EXTPOL .GT. 0 )   THEN
        IF(ERR1R .LE. EPS)   GO TO 7000
C      ELSE
C        IF( ERR2R .LE. EPS )   GO TO 7000
      END IF

      WRITE(LUPRT,840)   RRMAX*1.0E-3, EPS
      WRITE(LUPRT,860)   MESHN + ICOUNT, ERR1R

      IF(MESHN+ICOUNT .GE. MAXIT)   THEN
CWRN       WRITE(LUWRN,600) ICOUNT+MESHN
       IF(EXTPOL .GT. 0)   THEN
CWRN        WRITE(LUWRN,410)
       ELSE
CWRN        WRITE(LUWRN,420)
       END IF
       GO TO 7000
      END IF

      IF(NPMAX.GT.NPOINT-2)  THEN
CWRN       WRITE(LUWRN,400)
        IF(EXTPOL. GT. 0)   THEN
CWRN         WRITE(LUWRN,410)
        ELSE
CWRN         WRITE(LUWRN,420)
        END IF
       GO TO 7000
      END IF

C   DEFINE NEW MESHES
      ICOUNT=ICOUNT+1

      IF(MESHN .EQ. MAXMSH)   THEN
       DO 2030   MESH=1,MESHN-1
       MH0(MESH)=MH0(MESH+1)
       DH0(MESH)=DH0(MESH+1)
       DH0SQ(MESH)=DH0SQ(MESH+1)
       MSED(MESH)=MSED(MESH+1)
       DSED(MESH)=DSED(MESH+1)
       DO 2030   M=1,MODQTY
       MY(MESH,M)=MY(MESH+1,M)
 2030  CONTINUE
      ELSE
       MESHN=MESHN+1
       ICOUNT=ICOUNT-1
      END IF

C     IF((MSHRAT .EQ. 2) .OR. (IMESH .EQ. 1))   THEN
      IF(MSHRAT .EQ. 2)   THEN
       MH0(MESHN)= MH0(MESHN-1) + MH0(MESHN-1)/(MESHN-1)
       MSED(MESHN)= MSED(MESHN-1)+ MSED(MESHN-1)/(MESHN-1)
      ELSE
       MH0(MESHN)= MH0(MESHN-3)*2
       MSED(MESHN)= MSED(MESHN-3)*2
      END IF

      DH0(MESHN)= 1.0D0/MH0(MESHN)
      DH0SQ(MESHN)=1.0D0/(DBLE(MH0(MESHN))**2)
      IF(H1N.NE.0.0)    DSED(MESHN)=H1N/MSED(MESHN)

      I=MESHN-1
      RETURN 1
 7000 CONTINUE
CWRN      WRITE(LUWRN,620)EPS,ERR1A,ERR1R,ERR2A,ERR2R
CWRN      WRITE(LUWRN,*) ' *** SUB ACCRCY, RANGE (km): ',RKM

      RETURN
      END
