      block data blkdat
      
      INTEGER EXTPOL
      INTEGER FIXDZ, OPTMZ

      CHARACTER*8 MODEL
      CHARACTER*80 TITLE

      COMMON /CONTUR/ CNTR1(4,4)
      COMMON /FLAGG/ PLANE, NOVOL, NOLOSS, NOCYL, LARGE, SUMPL
      COMMON /FLAGPL/ FIRST, FLAGP, FLAGPU, EXTPOL, CORREC
      COMMON /MESH/ DZH0, DZH1, INPDZ, FIXDZ
      COMMON /MODEL/ MODEL
      COMMON /NORM/ N12221, N14241
      COMMON /PARAM3/ IMESH, NMESH, MSHRAT, OPTMZ
      COMMON /REC1/ TITLE
      COMMON /STARTR/ MODST
      COMMON /TIMING/ CPEIGV, CPEIGF, CPNEWP, CPFILE

      DATA FLAGPU /0.0/
      DATA PLANE, NOVOL / 0.0, 0 /
      DATA NOCYL, NOLOSS, LARGE, SUMPL / 0, 0, 0, 0.0 /
      DATA MODEL /'C-SNAP  '/
      DATA MODST / 0 /

      DATA TITLE /' '/
      DATA CPEIGV, CPEIGF, CPNEWP, CPFILE/ 4 * 0.0 /
C
C   CNTR1 KEEPS ZMIN, ZMAX, AND ZLEV INPUT PARAMETERS
C   FOR CONTOURED REPRESENTATIONS.
C
      DATA (CNTR1(1,J),J=1,4) / 60., 100., 5., 0. /
      DATA (CNTR1(2,J),J=1,4) / 60., 100., 5., 0. /
      DATA (CNTR1(3,J),J=1,4) / 60., 100., 5., 0. /
      DATA (CNTR1(4,J),J=1,4) / 1450., 1600., 10., 0. /

      DATA FLAGP/ 1.0 /
      DATA INPDZ, FIXDZ, OPTMZ/ 0, 0, 0 /
      DATA N12221, N14241 / 1, 0 /
      DATA NMESH, IMESH, MSHRAT / 4, 1, 0 /

      END
