C   CONDRC.FOR
      SUBROUTINE CONDRC( NP, FREQ, TITLE, IOP, SD, RDAR,
     & NRCVRS, ISHIFT,
     & INDX, INDY, NINDX, NINDY, TLOSS,
     & SECD, FLAG, AX, AY,
     & NOPT, ICF, PRSS, RPROF, BATHY, NSECT, HMAX, COHINC )

      INTEGER INDX( * ), INDY(*)

      CHARACTER*3 BWCOL
      CHARACTER*3 XBTYPE, YBTYPE
      CHARACTER*3 COHINC
      CHARACTER*16 OPTION
      CHARACTER*80 TITLE, TITLEX, TITLEY
      CHARACTER*80 FILENM

      REAL NRNG

      REAL RDAR( * )
      REAL TLOSS( * ), RPROF( * ), BATHY(1)
      REAL SECTOR(28)
      REAL SECD(NOPT,3)
      REAL FLAG(NOPT,ICF), AX(NOPT,6), AY(NOPT,7)

      DOUBLE PRECISION TWOPI, PI, OMEGA

      REAL PRSS(NRCVRS-ISHIFT,NP)

      COMMON /CONTUR/ CNTR1(4,4)
      COMMON /FLAGG/ PLANE, NOVOL, NOLOSS, NOCYL, LARGE, SUMPL
      COMMON /LUCONT/ LUCDR, LUBDR, LUCFR, LUBFR
      COMMON /LUNIT/ LUPLP, LUPLT, LUPRT
      COMMON /TRIGON/ TWOPI, PI, OMEGA
      COMMON /XAXC/ TITLEX, XBTYPE
      COMMON /YAXC/ TITLEY, YBTYPE

      DATA FLAGRC, DUMMY/0.0, 0.0/
      DATA CAY, NRNG/ 5.0, 5.0/
      DATA X1PL,Y1PL/2.0,2.0/,HGTPT,HGTC,LABPT,NDIV,
     & NARC/0.1,0.14,-3,1,5/,LABC,LWGT/-1,0/
      DATA SIGMA/8.0/

  120 FORMAT(5E15.4)
  150 FORMAT('CONDR,',A3,',',A3,'   ')
  401 FORMAT(1H ,F15.4,3X,'  NUMBER OF DATA POINTS ALONG THE X AXIS')
  402 FORMAT(1H ,F15.4,3X,'  NUMBER OF DATA POINTS ALONG THE Y AXIS')
  403 FORMAT(1H ,F15.4,3X,'  DIVX  ' )
  404 FORMAT(1H ,F15.4,3X,'  DIVY  ' )
  405 FORMAT(1H ,F15.4,3X,'  FLAGRC =0 ROWS, =1 COLUMNS')
  406 FORMAT(1H ,F15.4,3X,'  MIN DEPTH (m) ' )
  407 FORMAT(1H ,F15.4,3X,'  MAX DEPTH (m) ' )
  408 FORMAT(1H ,F15.4,3X,'  SOURCE DEPTH (m) ' )
  409 FORMAT(1H ,F15.4,3X,'  NUMBER OF GRID POINTS ALONG THE X AXIS ' )
  410 FORMAT(1H ,F15.4,3X,'  NUMBER OF GRID POINTS ALONG THE Y AXIS ' )
  411 FORMAT(1H ,F15.4,3X,'  FREQUENCY (Hz)' )
  412 FORMAT(1H ,F15.4,3X,'  DUMMY ' )
  413 FORMAT(1H ,F15.4,3X,'  CAY   ' )
  414 FORMAT(1H ,F15.4,3X,'  NRNG  ' )
  415 FORMAT(1H ,F15.4,3X,'  ZMIN ' )
  416 FORMAT(1H ,F15.4,3X,'  ZMAX ' )
  417 FORMAT(1H ,F15.4,3X,'  ZINC ' )
  418 FORMAT(1H ,F15.4,3X,'  X ORIGIN OF PLOT IN INCHES ' )
  419 FORMAT(1H ,F15.4,3X,'  SIGMA ' )
  420 FORMAT(1H ,F15.4,3X,'  Y ORIGIN OF PLOT IN INCHES ' )
  421 FORMAT(1H ,F15.4,3X,'  NSM   ' )
  422 FORMAT(1H ,F15.4,3X,'  HGTPT ' )
  423 FORMAT(1H ,F15.4,3X,'  HGTC ' )
  424 FORMAT(1H ,F15.4,3X,'  LABPT ' )
  425 FORMAT(1H ,F15.4,3X,'  NDIV ' )
  426 FORMAT(1H ,F15.4,3X,'  NARC ' )
  427 FORMAT(1H ,F15.4,3X,'  LABC ' )
  428 FORMAT(1H ,F15.4,3X,'  LWGT ' )
c  700 FORMAT('BOTTOM  -1')
  700 FORMAT('BOTTOM         1')
  800 FORMAT(A16)
  810 FORMAT(A20)
  820 FORMAT('Range (km)  ',17('    '))
  840 FORMAT('Depth (m)   ',17('    '))
  850 FORMAT(A80)

  900 FORMAT(1X,F15.4,3X,'  XLEFT',/,F16.4,4X,' XRIGHT',/,F16.4,3X,
     *'  X AXIS LENGTH IN CM ',/,F16.4,4X,' XINC')
  901 FORMAT(1X,F15.4,3X,'  YUP',/,F16.4,3X,'  YDOWN',/,F16.4,3X,
     *'  Y AXIS LENGTH IN CM ',/,F16.4,3X,'  YINC')
  950 FORMAT(1H ,F15.4,1X,'    RMIN',/,F16.4,2X,'   RMAX')
  960 FORMAT(1X, ' SUB CONDRC, FILENM : ',A30)
C
C  DEFINITION OF CONSTANTS.
C
      FILENM=' '

      DIVX=1.0E-3
      DIVY=1.0
      XBTYPE='LIN'
      YBTYPE='LIN'
      WRITE(TITLEX,820)
      WRITE(TITLEY,840)
C
      IF( FLAG(IOP,4) .GT. 0.0 )   THEN
        BWCOL= 'COL'
      ELSE
        BWCOL= 'B/W'
      END IF

      NPY= NINDY

      WRITE(OPTION,150)   COHINC, BWCOL

      WRITE(LUCDR,800) OPTION
      WRITE(LUCDR,850) TITLE

      FILENM(1:16)= '"INPUT_FILE".BDR'
      WRITE(LUPRT,960) FILENM(1:20)
      WRITE(LUCDR,810) FILENM

      WRITE(LUCDR,850) TITLEX

C   RMIN,RMAX
      WRITE(LUCDR,950) SECD(IOP,1), SECD(IOP,2)

C   XLEFT,XRIGHT,X AXIS LENGTH,XINC
      XLEN=ABS((AX(IOP,1)-AX(IOP,2))/AX(IOP,3))
      XINC= MIN(AX(IOP,2) - AX(IOP,1), AX(IOP,4))
      WRITE(LUCDR,900) AX(IOP,1), AX(IOP,2), XLEN, XINC

      WRITE(LUCDR,850) TITLEY

C   YUP,YDOWN,Y AXIS LENGTH,YINC
      YLEN=ABS((AY(IOP,1)-AY(IOP,2))/AY(IOP,3))
      YINC= MIN(AY(IOP,2) - AY(IOP,1), AY(IOP,4))
      WRITE(LUCDR,901) AY(IOP,1), AY(IOP,2), YLEN, YINC

C   NUMBER OF DATA POINTS ALONG THE X AND Y AXES
      WRITE(LUCDR,401) FLOAT( NINDX )
      WRITE(LUCDR,402) FLOAT( NPY )

      WRITE(LUCDR,403) DIVX
      WRITE(LUCDR,404) DIVY
      WRITE(LUCDR,405) FLAGRC

C   MIN AND MAX VALUES ON Y AXIS
      WRITE(LUCDR,406) RDAR(INDY(1))
      WRITE(LUCDR,407) RDAR(INDY(NINDY))

C   SOURCE DEPTH (m)
      WRITE(LUCDR,408) SD

C   NUMBER OF GRID POINTS ALONG THE X AND Y AXES
      WRITE(LUCDR,409) FLOAT( NINDX )
      WRITE(LUCDR,410) FLOAT( NPY )

C   FREQUENCY
      WRITE(LUCDR,411) FREQ

C   DUMMY
      WRITE(LUCDR,412) DUMMY
C CAY
      WRITE(LUCDR,413) CAY
C NRNG
      WRITE(LUCDR,414) NRNG

C   CONTOUR LEVELS
      WRITE(LUCDR,415) CNTR1(1,1)
      WRITE(LUCDR,416) CNTR1(1,2)
      WRITE(LUCDR,417) CNTR1(1,3)

C   X1PL : X ORIGIN OF PLOT IN INCHES
      WRITE(LUCDR,418) X1PL

C   SIGMA FOR STATISTIC ON FIGURE OF MERIT
      WRITE(LUCDR,419) SIGMA

C   Y1PL : Y ORIGIN OF PLOT IN INCHES
      WRITE(LUCDR,420) Y1PL

C   NUMBER OF SMOOTHINGS
      NSM= MAX(0, NINT(CNTR1(1,4)))
      WRITE(LUCDR,421) FLOAT( NSM )

C   CHAR HEIGHT ON DATA POINTS
      WRITE(LUCDR,422) HGTPT

C   CHAR HEIGHT ON CONTOUR LINES
      WRITE(LUCDR,423) HGTC

      WRITE(LUCDR,424) FLOAT( LABPT )
C
      WRITE(LUCDR,425) FLOAT( NDIV )
C
      WRITE(LUCDR,426) FLOAT( NARC )
C
      WRITE(LUCDR,427) FLOAT( LABC )
C
      WRITE(LUCDR,428) FLOAT( LWGT )

C   BOTTOM SHADING
      WRITE(LUCDR,700)
      WRITE(LUCDR,*) RPROF(1)/divx, 
     &    MAX( HMAX, MAX(AY(IOP,1),AY(IOP,2)) )
      DO 1500   ISECT=1,NSECT
      WRITE(LUCDR,*) RPROF(ISECT)/divx, BATHY(ISECT)
 1500 CONTINUE
      WRITE(LUCDR,*) 1.0E-3*SECD(IOP,2)/divx, BATHY(NSECT)
      WRITE(LUCDR,*) 1.0E-3*SECD(IOP,2)/divx,
     &               MAX( HMAX, MAX(AY(IOP,1),AY(IOP,2)) )
      write(LUCDR,'(a)') '@EOF'
C      CLOSE(UNIT=26)

      DO 1700   I=3,28
      SECTOR(I)=0.0
 1700 CONTINUE
C   NUMBER OF DATA POINTS ALONG THE X AND Y AXES
      SECTOR(1)= NINDX
      SECTOR(2)= NPY

C   SECTOR(4) IS A FLAG MAINTAINED FOR COMPATIBILITY WITH
C   OTHER PROGRAMS
      SECTOR(4)=1.0
      SECTOR(5)=PLANE
      SECTOR(6)=SECD(IOP,3)
      SECTOR(7)=SECD(IOP,1)
      SECTOR(8)=SECD(IOP,2)
      WRITE(LUBDR,120)   ( SECTOR(I), I=1, 28 )


C      WRITE(LUPRT,*) ' SUB CONDRC, NINDX, NINDY ',NINDX,NINDY

      IF( RDAR(1) .EQ. 0)   THEN
        WRITE(LUBDR,120)( 200.0, JJ=1, NINDX )
      END IF

      DO 2000   IRD= 1 + ISHIFT, NINDY
      CALL TLCPLE( PRSS, NP, NRCVRS - ISHIFT, INDY(IRD)-ISHIFT,
     & INDX, NINDX,  TLOSS )
      WRITE(LUBDR,120)    ( TLOSS(JJ), JJ=1, NINDX )
 2000 CONTINUE


C      CLOSE(UNIT=LUBDR)
      RETURN

      END
