C  ETIME_VMS.F
      REAL FUNCTION ETIME(CPSEC)
      DIMENSION CPSEC(2)
      INTEGER*4 IT4
      DOUBLE PRECISION IT8
      EQUIVALENCE (IT4,IT8)

      ISTAT=LIB$STAT_TIMER(2,IT4)
      ETIME=IT4/100.0

      RETURN
      END