C TLCPLE.FOR
      SUBROUTINE TLCPLE(PRSS, NR, NRCVRS, IRCVR,
     & INDX, NINDX, TLOSS)

      REAL TLOSS( * )
      INTEGER INDX( * )
      REAL PRSS(NRCVRS,NR)

      DO 1400 I= 1, NINDX
        TLOSS(I)= PRSS(IRCVR, INDX(I))
 1400 CONTINUE

      RETURN
      END
